### PR TITLE
Add ID to Submit Button ID so not violating unique ID per page rule.

### PR DESCRIPTION
**Pull request by MikeiLL**
Sorry it's not more. I love this project and hope to contribute further.

### CODE REVIEW

**Comment by ahmadawais** [comment]
@MikeiLL any contributions are welcomed. Can you share more about what this PR does and maybe show a screenshot?

**Comment by MikeiLL** [comment]
Well there's not much to share in a screenshot. The way it is currently setup, the html id for the submit buttons all have id=submit, which creates multiple items with the same ID in the admin page. So now each submit button will have the id=submit_[section_id] so the IDs are unique. Make sense?

**Review by ahmadawais — APPROVED** [review]
Looks good to me! 🔥

**Comment by ahmadawais** [comment]
Thanks @MikeiLL would love more contribution from your end. 👍

**Pull request merged**
